#Script generated by: Aaron D. Ramirez-Sanchez 
#Goal: To perform enrichment analysis tables and objects

##ENVIRONMENT
library(clusterProfiler)
library(ReactomePA)
library(enrichplot)
library(msigdbr)

##FUNCTIONS
# Function to put in compareCluster
gse_fun <- function(gene_id = ENTREZID, term = msigdbr_t2g) {
  enricher(gene = gene_id, TERM2GENE = term, pvalueCutoff = 0.05)
}


##INPUT

#reading merged DEG 
DEG.merged <- read.csv(file = "./output/tables/DEG/comparisons_merged.csv", header = T, stringsAsFactors = F)

#Filters used for the DEG
L2FC.filter <- 1.0
p.adj.filter <- 0.01

# Getting human hallmark dataset
h_gene_set <- msigdbr(species = "Homo sapiens", category = "H")
msigdbr_t2g <- h_gene_set %>% 
  dplyr::distinct(gs_name, entrez_gene) %>% 
  as.data.frame()

##MAIN

#Filtering data
DEG.merged <- DEG.merged[(abs(DEG.merged$log2FoldChange) > L2FC.filter & !is.na(DEG.merged$log2FoldChange)) & 
                                    (DEG.merged$padj < p.adj.filter & !is.na(DEG.merged$padj)), ]

### Doing enrichments

#REACTOME enrichment
DEG.Pathway <- compareCluster(ENTREZID~Direction+Comparison, data=DEG.merged, fun="enrichPathway", readable=T)
DEG.Pathway@compareClusterResult$minuslog10p.adjust <- -log10(DEG.Pathway@compareClusterResult$p.adjust)
DEG.Pathway.pw <- pairwise_termsim(DEG.Pathway)

#GO: Molecular function
DEG.mf <- compareCluster(ENTREZID~Direction+Comparison, data=DEG.merged, fun="enrichGO", OrgDb = org.Hs.eg.db, ont = "MF", readable=T) 
DEG.mf@compareClusterResult$minuslog10p.adjust <- -log10(DEG.mf@compareClusterResult$p.adjust)
DEG.mf.pw <- pairwise_termsim(DEG.mf)
DEG.mf.pw.simp <- simplify(DEG.mf.pw, cutoff=0.7, by="p.adjust", select_fun=min)

#GO: Biological process
DEG.bp <- compareCluster(ENTREZID~Direction+Comparison, data=DEG.merged, fun="enrichGO", OrgDb = org.Hs.eg.db, ont = "BP", readable=T) 
DEG.bp@compareClusterResult$minuslog10p.adjust <- -log10(DEG.bp@compareClusterResult$p.adjust)
DEG.bp.pw <- pairwise_termsim(DEG.bp)
DEG.bp.pw.simp <- simplify(DEG.bp.pw, cutoff=0.7, by="p.adjust", select_fun=min)

#GO: Celullar component
DEG.cc <- compareCluster(ENTREZID~Direction+Comparison, data=DEG.merged, fun="enrichGO", OrgDb = org.Hs.eg.db, ont = "CC", readable=T) 
DEG.cc@compareClusterResult$minuslog10p.adjust <- -log10(DEG.cc@compareClusterResult$p.adjust)
DEG.cc.pw <- pairwise_termsim(DEG.cc)
DEG.cc.pw.simp <- simplify(DEG.cc.pw, cutoff=0.7, by="p.adjust", select_fun=min)

#KEGG enrichment
DEG.kegg <- compareCluster(ENTREZID~Direction+Comparison, data=DEG.merged, fun="enrichKEGG") 
DEG.kegg@compareClusterResult$minuslog10p.adjust <- -log10(DEG.kegg@compareClusterResult$p.adjust)
DEG.kegg.pw <- pairwise_termsim(DEG.kegg)

#GSE enrichment
DEG.gse <- compareCluster(ENTREZID~Direction+Comparison, data = DEG.merged, fun = gse_fun)
DEG.gse@compareClusterResult$minuslog10p.adjust <- -log10(DEG.gse@compareClusterResult$p.adjust)
DEG.gse.pw <- pairwise_termsim(DEG.gse)

##OUTPUT

#SAVING enrichments
write.csv(DEG.Pathway, 
          file="./output/tables/enrichments/DEG.Pathway.csv", 
          row.names = F, quote = F)
write.table(DEG.Pathway, 
            file="./output/tables/enrichments/DEG.Pathway.txt", 
            row.names = F, quote = F, sep = "\t")
write.csv(DEG.mf, 
          file="./output/tables/enrichments/DEG.mf.csv", 
          row.names = F, quote = F)
write.csv(DEG.bp, 
          file="./output/tables/enrichments/DEG.bp.csv", 
          row.names = F, quote = F)
write.csv(DEG.cc, 
          file="./output/tables/enrichments/DEG.cc.csv", 
          row.names = F, quote = F)
write.csv(DEG.kegg, 
          file="./output/tables/enrichments/DEG.kegg.csv", 
          row.names = F, quote = F)
write.csv(DEG.gse, 
          file="./output/tables/enrichments/DEG.gse.csv", 
          row.names = F, quote = F)

#Saving enrichment objects
saveRDS(DEG.Pathway, "./output/objects/enrichments/DEG/Pathway.RDS")
saveRDS(DEG.mf, "./output/objects/enrichments/DEG/mf.RDS")
saveRDS(DEG.bp, "./output/objects/enrichments/DEG/bp.RDS")
saveRDS(DEG.cc, "./output/objects/enrichments/DEG/cc.RDS")
saveRDS(DEG.kegg, "./output/objects/enrichments/DEG/kegg.RDS")
saveRDS(DEG.gse, "./output/objects/enrichments/DEG/gse.RDS")

saveRDS(DEG.Pathway.pw, "./output/objects/enrichments/DEG/pw/Pathway.pw.RDS")
saveRDS(DEG.mf.pw.simp, "./output/objects/enrichments/DEG/pw/mf.pw.RDS")
saveRDS(DEG.bp.pw.simp, "./output/objects/enrichments/DEG/pw/bp.pw.RDS")
saveRDS(DEG.cc.pw.simp, "./output/objects/enrichments/DEG/pw/cc.pw.RDS")
saveRDS(DEG.kegg.pw, "./output/objects/enrichments/DEG/pw/kegg.pw.RDS")
saveRDS(DEG.gse.pw, "./output/objects/enrichments/DEG/pw/gse.pw.RDS")
