#Script generated by: Aaron D. Ramirez-Sanchez 
#Goal: To perform enrichment analysis tables and objects

##ENVIRONMENT
library(clusterProfiler)
library(ReactomePA)
library(enrichplot)
library(msigdbr)

##FUNCTIONS
# Function to put in compareCluster
gse_fun <- function(gene_id = ENTREZID, term = msigdbr_t2g) {
  enricher(gene = gene_id, TERM2GENE = term, pvalueCutoff = 0.05)
}

##INPUT

#reading merged DEG 
DEG.merged <- read.csv(file = "./output/tables/DEG/extended_comparisons_mergedv2.csv", header = T, stringsAsFactors = F)

# Getting human hallmark dataset
h_gene_set <- msigdbr(species = "Homo sapiens", category = "H")
msigdbr_t2g <- h_gene_set %>% 
  dplyr::distinct(gs_name, entrez_gene) %>% 
  as.data.frame()

##MAIN
### Doing enrichments

#REACTOME enrichment
DEG.Pathway <- compareCluster(ENTREZID~Cluster, data=DEG.merged, fun="enrichPathway", readable=T)
DEG.Pathway@compareClusterResult$minuslog10p.adjust <- -log10(DEG.Pathway@compareClusterResult$p.adjust)
DEG.Pathway.pw <- pairwise_termsim(DEG.Pathway)

#GO: Molecular function
DEG.mf <- compareCluster(ENTREZID~Cluster, data=DEG.merged, fun="enrichGO", OrgDb = org.Hs.eg.db, ont = "MF", readable=T) 
DEG.mf@compareClusterResult$minuslog10p.adjust <- -log10(DEG.mf@compareClusterResult$p.adjust)
DEG.mf.pw <- pairwise_termsim(DEG.mf)
DEG.mf.pw.simp <- simplify(DEG.mf.pw, cutoff=0.7, by="p.adjust", select_fun=min)

#GO: Biological process
DEG.bp <- compareCluster(ENTREZID~Cluster, data=DEG.merged, fun="enrichGO", OrgDb = org.Hs.eg.db, ont = "BP", readable=T) 
DEG.bp@compareClusterResult$minuslog10p.adjust <- -log10(DEG.bp@compareClusterResult$p.adjust)
DEG.bp.pw <- pairwise_termsim(DEG.bp)
DEG.bp.pw.simp <- simplify(DEG.bp.pw, cutoff=0.7, by="p.adjust", select_fun=min)

#GO: Celullar component
DEG.cc <- compareCluster(ENTREZID~Cluster, data=DEG.merged, fun="enrichGO", OrgDb = org.Hs.eg.db, ont = "CC", readable=T) 
DEG.cc@compareClusterResult$minuslog10p.adjust <- -log10(DEG.cc@compareClusterResult$p.adjust)
DEG.cc.pw <- pairwise_termsim(DEG.cc)
DEG.cc.pw.simp <- simplify(DEG.cc.pw, cutoff=0.7, by="p.adjust", select_fun=min)

#KEGG enrichment
DEG.kegg <- compareCluster(ENTREZID~Cluster, data=DEG.merged, fun="enrichKEGG") 
DEG.kegg@compareClusterResult$minuslog10p.adjust <- -log10(DEG.kegg@compareClusterResult$p.adjust)
DEG.kegg.pw <- pairwise_termsim(DEG.kegg)

#GSE enrichment
DEG.gse <- compareCluster(ENTREZID~Cluster, data=DEG.merged, fun=gse_fun) 
DEG.gse@compareClusterResult$minuslog10p.adjust <- -log10(DEG.gse@compareClusterResult$p.adjust)
DEG.gse.pw <- pairwise_termsim(DEG.gse)

##OUTPUT

#SAVING enrichments
write.csv(DEG.Pathway, 
          file="./output/tables/enrichments/clusters.Pathwayv2.csv", 
          row.names = F, quote = F)
write.csv(DEG.mf, 
          file="./output/tables/enrichments/clusters.mfv2.csv", 
          row.names = F, quote = F)
write.csv(DEG.bp, 
          file="./output/tables/enrichments/clusters.bpv2.csv", 
          row.names = F, quote = F)
write.csv(DEG.cc, 
          file="./output/tables/enrichments/clusters.ccv2.csv", 
          row.names = F, quote = F)
write.csv(DEG.kegg, 
          file="./output/tables/enrichments/clusters.keggv2.csv", 
          row.names = F, quote = F)
write.csv(DEG.gse, 
          file="./output/tables/enrichments/clusters.gsev2.csv", 
          row.names = F, quote = F)

#Saving enrichment objects
saveRDS(DEG.Pathway, "./output/objects/enrichments/clusters/Pathwayv2.RDS")
saveRDS(DEG.mf, "./output/objects/enrichments/clusters/mfv2.RDS")
saveRDS(DEG.bp, "./output/objects/enrichments/clusters/bpv2.RDS")
saveRDS(DEG.cc, "./output/objects/enrichments/clusters/ccv2.RDS")
saveRDS(DEG.kegg, "./output/objects/enrichments/clusters/keggv2.RDS")
saveRDS(DEG.gse, "./output/objects/enrichments/clusters/gsev2.RDS")

saveRDS(DEG.Pathway.pw, "./output/objects/enrichments/clusters/pw/Pathway.pwv2.RDS")
saveRDS(DEG.mf.pw.simp, "./output/objects/enrichments/clusters/pw/mf.pwv2.RDS")
saveRDS(DEG.bp.pw.simp, "./output/objects/enrichments/clusters/pw/bp.pwv2.RDS")
saveRDS(DEG.cc.pw.simp, "./output/objects/enrichments/clusters/pw/cc.pwv2.RDS")
saveRDS(DEG.kegg.pw, "./output/objects/enrichments/clusters/pw/kegg.pwv2.RDS")
saveRDS(DEG.gse.pw, "./output/objects/enrichments/clusters/pw/gse.pwv2.RDS")
