#Script generated by: Aaron D. Ramirez-Sanchez 
#Goal: To plot enrcihment analysis of DEG

##ENVIRONMENT
library(enrichplot)
library(clusterProfiler)
library(ReactomePA)
library(ggplot2)


##FUNCTIONS

#FUN: theme.plain
theme.plain <- function(p, base_size = 10, base_family = "ArialMT") {
  p <- p + theme_linedraw(base_size = base_size, base_family = base_family) %+replace%
    theme(panel.background = element_blank(),
          #panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line = element_line(color="black", size=0.75),
          axis.ticks = element_line(size=0.75),
          axis.text = element_text(size=base_size, family="ArialMT", face="plain"),
          strip.background = element_blank(),
          strip.text = element_text(size=base_size, family="ArialMT", face="plain"),
          legend.key = element_blank(),
          legend.text = element_text(size=base_size, family = "ArialMT", face="plain"),
          complete = TRUE,
          plot.title = element_text(hjust=0.5))
  return(p)
}

#FUN: import.files, import all files from a folder
import.files <- function(input_folder, pattern_files){
  # Make a vector of all your file paths
  file_paths <- list.files(path = here::here(input_folder), pattern = pattern_files, full.names = TRUE)
  # Make a vector of file names
  file_names <-  gsub(pattern = pattern_files, replacement = "", x = basename(file_paths))
  # Read all your data into a list
  data_list <- lapply(file_paths, readRDS)
  # Assign file names to list elements
  names(data_list) <- file_names
  return(data_list)
}

##INPUT

#colors: Danger Red, Tap Shoe and Blue Blossom
pallete_condition <- c("#D9514E", "#2A2B2D", "#2DA8D8")
#colors: Danger Red and 1/2, Tap Shoe and 1/2; and Blue Blossom and 1/2
pallete_condition_updown <- c("#D9514E","#FFACAA", "#2A2B2D","#6B6E73", "#2DA8D8","#7ECDEA")

#Reading enrichment objects
enrichment_objects <- import.files(input_folder = "./output/objects/enrichments/clusters/", pattern_files = "v2\\.RDS")

##MAIN

###Plotting
enrichment_dotplots <- lapply(enrichment_objects, function(enrichment) {
  dotplot(enrichment, 
          x="Cluster", 
          showCategory=5, 
          color = "minuslog10p.adjust", 
          font.size = 9, label_format = 50) + 
    scale_colour_gradient(low="#D0E0F3", high="#257EE4")
})

##OUTPUT

#Saving dotplots
pdf(file = "./output/plots/enrichments_dotplots_clustersv2.pdf", width=7, height=7,  family = "ArialMT")

theme.plain(enrichment_dotplots$Pathway) +
  theme(axis.text.x = element_text(angle = 90), 
        axis.text.y = element_text(size = 8, lineheight = 0.7), 
        strip.text.x = element_text(size = 9, vjust=0.5)) +
  labs(colour = "-log10(adj. P-value)") +
  ggtitle("Pathway Enrichment")

theme.plain(enrichment_dotplots$mf) +
  theme(axis.text.x = element_text(angle = 90), 
        axis.text.y = element_text(size = 8, lineheight = 0.7), 
        strip.text.x = element_text(size = 9, vjust=0.5)) +
  labs(colour = "-log10(adj. P-value)") +
  ggtitle("GO: Molecular function Enrichment")

theme.plain(enrichment_dotplots$bp) +
  theme(axis.text.x = element_text(angle = 90), 
        axis.text.y = element_text(size = 8, lineheight = 0.7), 
        strip.text.x = element_text(size = 9, vjust=0.5)) +
  labs(colour = "-log10(adj. P-value)") +
  ggtitle("GO: Biological process Enrichment")

theme.plain(enrichment_dotplots$cc) +
  theme(axis.text.x = element_text(angle = 90), 
        axis.text.y = element_text(size = 8, lineheight = 0.7), 
        strip.text.x = element_text(size = 9, vjust=0.5)) +
  labs(colour = "-log10(adj. P-value)") +
  ggtitle("GO: Celullar component Enrichment")

theme.plain(enrichment_dotplots$kegg) +
  theme(axis.text.x = element_text(angle = 90), 
        axis.text.y = element_text(size = 8, lineheight = 0.7), 
        strip.text.x = element_text(size = 9, vjust=0.5)) +
  labs(colour = "-log10(adj. P-value)") +
  ggtitle("Kegg Enrichment")

theme.plain(enrichment_dotplots$gse) +
  theme(axis.text.x = element_text(angle = 90), 
        axis.text.y = element_text(size = 8, lineheight = 0.7), 
        strip.text.x = element_text(size = 9, vjust=0.5)) +
  labs(colour = "-log10(adj. P-value)") +
  ggtitle("GSE Enrichment")

dev.off()
