#Script generated by: Aaron D. Ramirez-Sanchez 
#Goal: To format metadata and create a sample_sample conversion

##ENVIRONMENT
library(ggplot2)
library(EnhancedVolcano)
library(ComplexHeatmap)
library(eulerr)
library(patchwork)

##FUNCTIONS
#####PLOTS

theme.plain <- function(p, base_size = 10, base_family = "ArialMT") {
  p <- p + theme_linedraw(base_size = base_size, base_family = base_family) %+replace%
    theme(panel.background = element_blank(),
          #panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line = element_line(color="black", size=0.75),
          axis.ticks = element_line(size=0.75),
          axis.text = element_text(size=base_size, family="ArialMT", face="plain"),
          strip.background = element_blank(),
          strip.text = element_text(size=base_size, family="ArialMT", face="plain"),
          legend.key = element_blank(),
          legend.text = element_text(size=base_size, family = "ArialMT", face="plain"),
          complete = TRUE,
          plot.title = element_text(hjust=0.5))
  return(p)
}


##INPUT
coldata <- read.delim(file = "./data/processed/metadata/extended_metadata.tsv", sep = "\t", row.names = 1)

#reading merged DEG 
DEG.merged <- read.csv(file = "./output/tables/DEG/comparisons_merged.csv", header = T, stringsAsFactors = F)

#Filters used for the DEG
L2FC.filter <- 1.0
p.adj.filter <- 0.01

RNA.ref <- read.table("/Users/R_projects/Oslo/results/eQTL/references/Homo_sapiens.GRCh37.75.genes.bed", sep = "\t", header = F)
names(RNA.ref) <- c("chr", "start_pos", "end_pos", "strand", "ENSEMBL", "SYMBOL")
RNA.ref <- RNA.ref[!duplicated(RNA.ref$ENSEMBL),]
Y.genes <- RNA.ref[RNA.ref$chr == "Y", ]$ENSEMBL

#colors: Danger Red, Tap Shoe and Blue Blossom
pallete_condition <- c("#D9514E", "#2A2B2D", "#2DA8D8")
#colors: Danger Red and 1/2, Tap Shoe and 1/2; and Blue Blossom and 1/2
pallete_condition_updown <- c("#D9514E","#FFACAA", "#2A2B2D","#6B6E73", "#2DA8D8","#7ECDEA")

##MAIN

#Filtering data
DEG.merged <- DEG.merged[(abs(DEG.merged$log2FoldChange) > L2FC.filter & !is.na(DEG.merged$log2FoldChange)) & 
                           (DEG.merged$padj < p.adj.filter & !is.na(DEG.merged$padj)), ]
DEG.merged$Direction <- factor(DEG.merged$Direction, levels = c("Upregulated", "Downregulated"))
DEG.merged <- DEG.merged[!DEG.merged$ENSEMBL %in% Y.genes, ]

#plot of genes up and down
p <- ggplot(DEG.merged, aes(x = Comparison, fill = Direction)) +
  geom_bar(position = "dodge") +
  geom_text(aes(label = ..count..), stat = "count", position = position_dodge(0.9), vjust = -0.5) +
  scale_fill_manual(values = c("#b2182b","#2166ac"))

#plot for vulcanos
TCDvsCTRL <- DEG.merged[DEG.merged$Comparison == "TCDvsCTRL",]
UCDvsCTRL <- DEG.merged[DEG.merged$Comparison == "UCDvsCTRL",]
UCDvsTCD <- DEG.merged[DEG.merged$Comparison == "UCDvsTCD",]

shared.ENSEMBL <- intersect(UCDvsCTRL$ENSEMBL, UCDvsTCD$ENSEMBL)

p.volcan1 <- EnhancedVolcano(TCDvsCTRL, lab = TCDvsCTRL$SYMBOL,
                             title= "TCDvsCTRL",
                             x = 'log2FoldChange',
                             y = 'padj',
                             pCutoff = 0.01
) + xlim(-10, 10)
p.volcan2 <- EnhancedVolcano(UCDvsCTRL, lab = UCDvsCTRL$SYMBOL,
                             title= "UCDvsCTRL",
                             x = 'log2FoldChange',
                             y = 'padj',
                             pCutoff = 0.01
) + xlim(-10, 10)
p.volcan3 <- EnhancedVolcano(UCDvsTCD, lab = UCDvsTCD$SYMBOL,
                             title= "UCDvsTCD",
                             x = 'log2FoldChange',
                             y = 'padj',
                             pCutoff = 0.01
) + xlim(-10, 10)

#Euler diagram
#Creating function to create matrix with the DEG 
list.up <- list(TCDvsCTRL = TCDvsCTRL[TCDvsCTRL$Direction == "Upregulated",]$ENSEMBL,
                  UCDvsCTRL = UCDvsCTRL[UCDvsCTRL$Direction == "Upregulated",]$ENSEMBL,
                  UCDvsTCD = UCDvsTCD[UCDvsTCD$Direction == "Upregulated",]$ENSEMBL
)
m.up.genes <- list_to_matrix(list.up)

list.down <- list(TCDvsCTRL = TCDvsCTRL[TCDvsCTRL$Direction == "Downregulated",]$ENSEMBL,
                  UCDvsCTRL = UCDvsCTRL[UCDvsCTRL$Direction == "Downregulated",]$ENSEMBL,
                  UCDvsTCD = UCDvsTCD[UCDvsTCD$Direction == "Downregulated",]$ENSEMBL
)

m.down.genes <- list_to_matrix(list.down)

fit.up <- euler(m.up.genes, shape = "ellipse")
fit.down <- euler(m.down.genes, shape = "ellipse")

p.eu.up <- plot(fit.up,
                quantities = TRUE,
                edges = F,
                fills = pallete_condition_updown[c(5,1,2)],
                labels = list(font = 2, fontsize = 12),
                main = "Upregulated")
p.eu.down <- plot(fit.down,
                  quantities = TRUE,
                  edges = F,
                  fills = pallete_condition_updown[c(5,1,2)],
                  labels = list(font = 2, fontsize = 12),
                  main = "Downregulated")


shared.UCDvsCTRL <- UCDvsCTRL[UCDvsCTRL$ENSEMBL %in% shared.ENSEMBL,]
rownames(shared.UCDvsCTRL) <- shared.UCDvsCTRL$ENSEMBL
shared.UCDvsTCD <- UCDvsTCD[UCDvsTCD$ENSEMBL %in% shared.ENSEMBL,]
rownames(shared.UCDvsTCD) <- shared.UCDvsTCD$ENSEMBL

shared.UCDvsCTRL <- shared.UCDvsCTRL[shared.ENSEMBL,] 
shared.UCDvsTCD <- shared.UCDvsTCD[shared.ENSEMBL,]

colnames(shared.UCDvsCTRL) <- paste0(colnames(shared.UCDvsCTRL), "_UCDvsCTRL")
colnames(shared.UCDvsTCD) <- paste0(colnames(shared.UCDvsTCD), "_UCDvsTCD")

shared.DEG <- cbind(shared.UCDvsCTRL, shared.UCDvsTCD)

ggplot(data = shared.DEG,
       mapping = aes(x = log2FoldChange_UCDvsTCD,
                     y = log2FoldChange_UCDvsCTRL)) +
  geom_point()

concordance.p <- ggplot(data = shared.DEG,
       mapping = aes(x = log2FoldChange_UCDvsTCD,
                     y = log2FoldChange_UCDvsCTRL)) + 
  geom_point(#aes(colour = Overlap), 
             alpha = 0.3, size = 2) +
  geom_text_repel(aes(label = ifelse(
    abs(log2FoldChange_UCDvsTCD) > 2.5 &
      abs(log2FoldChange_UCDvsCTRL) > 2.5, 
    SYMBOL_UCDvsTCD, "")),
                  max.overlaps = 15)+
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  ylab("L2FC in UCD vs CTRL") +
  xlab("L2FC in UCD vs TCD") +
  xlim(-8, 8) +
  ylim(-8, 8) +
  coord_fixed() +
  #scale_color_manual(values=c("#8CED3C", "#4B4BCD", "#30BCBC")) +
  ggtitle("Shared DE genes")

##UPSET plots
# compare two UpSet plots

m.comb.up <-  make_comb_mat(list.up)
m.comb.down <-  make_comb_mat(list.down)

max1 <- max(c(set_size(m.comb.up), set_size(m.comb.down)))
max2 <- max(c(comb_size(m.comb.up), comb_size(m.comb.down)))

upset.plot <- UpSet(m.comb.up, 
                    top_annotation = upset_top_annotation(m.comb.up, ylim = c(0, max2)),
                    right_annotation = upset_right_annotation(m.comb.up, ylim = c(0, max1)),
                    column_title = "Upregulated") +
  UpSet(m.comb.down, 
        top_annotation = upset_top_annotation(m.comb.down, ylim = c(0, max2)),
        right_annotation = upset_right_annotation(m.comb.down, ylim = c(0, max1)),
        column_title = "Downregulated")


##OUTPUT

pdf(file = "./output/plots/DEG_overview.pdf", width=6, height=4.5,  family = "ArialMT")
theme.plain(p)
dev.off()

pdf(file = "./output/plots/DEG_vulcanos.pdf", width=6, height=6,  family = "ArialMT")
theme.plain(p.volcan1) + theme(legend.position = "none")
theme.plain(p.volcan2) + theme(legend.position = "none")
theme.plain(p.volcan3) + theme(legend.position = "none")
dev.off()

pdf(file = "./output/plots/DEG_up_euler.pdf", width=5, height=4,  family = "ArialMT")
p.eu.up
dev.off()

pdf(file = "./output/plots/DEG_down_euler.pdf", width=5, height=4,  family = "ArialMT")
p.eu.down
dev.off()

pdf(file = "./output/plots/DEG_concordance.pdf", width=5, height=4,  family = "ArialMT")
theme.plain(concordance.p)
dev.off()

pdf(file = "./output/plots/DEG_general_upset.pdf", width=6, height=4,  family = "ArialMT")
upset.plot
dev.off()
