#Script generated by: Aaron D. Ramirez-Sanchez 
#Goal: To format metadata and create a sample_sample conversion

##ENVIRONMENT
library(ggplot2)
library(EnhancedVolcano)

##FUNCTIONS
#####PLOTS

theme.plain <- function(p, base_size = 10, base_family = "ArialMT") {
  p <- p + theme_linedraw(base_size = base_size, base_family = base_family) %+replace%
    theme(panel.background = element_blank(),
          #panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line = element_line(color="black", size=0.75),
          axis.ticks = element_line(size=0.75),
          axis.text = element_text(size=base_size, family="ArialMT", face="plain"),
          strip.background = element_blank(),
          strip.text = element_text(size=base_size, family="ArialMT", face="plain"),
          legend.key = element_blank(),
          legend.text = element_text(size=base_size, family = "ArialMT", face="plain"),
          complete = TRUE,
          plot.title = element_text(hjust=0.5))
  return(p)
}


##INPUT
coldata <- read.delim(file = "./data/processed/metadata/extended_metadata.tsv", sep = "\t", row.names = 1)

#reading merged DEG 
DEG.merged <- read.csv(file = "./output/tables/DEG/clusters_comparisons_merged.csv", header = T, stringsAsFactors = F)

#Filters used for the DEG
L2FC.filter <- 1.0
p.adj.filter <- 0.01

RNA.ref <- read.table("/Users/R_projects/Oslo/results/eQTL/references/Homo_sapiens.GRCh37.75.genes.bed", sep = "\t", header = F)
names(RNA.ref) <- c("chr", "start_pos", "end_pos", "strand", "ENSEMBL", "SYMBOL")
RNA.ref <- RNA.ref[!duplicated(RNA.ref$ENSEMBL),]
Y.genes <- RNA.ref[RNA.ref$chr == "Y", ]$ENSEMBL

#colors: Danger Red, Tap Shoe and Blue Blossom
pallete_condition <- c("#D9514E", "#2A2B2D", "#2DA8D8")
#colors: Danger Red and 1/2, Tap Shoe and 1/2; and Blue Blossom and 1/2
pallete_condition_updown <- c("#D9514E","#FFACAA", "#2A2B2D","#6B6E73", "#2DA8D8","#7ECDEA")

##MAIN

#Filtering data
DEG.merged <- DEG.merged[(abs(DEG.merged$log2FoldChange) > L2FC.filter & !is.na(DEG.merged$log2FoldChange)) & 
                           (DEG.merged$padj < p.adj.filter & !is.na(DEG.merged$padj)), ]
DEG.merged$Direction <- factor(DEG.merged$Direction, levels = c("Upregulated", "Downregulated"))
DEG.merged <- DEG.merged[!DEG.merged$ENSEMBL %in% Y.genes, ]

#plot of genes up and down
p <- ggplot(DEG.merged, aes(x = Comparison, fill = Direction)) +
  geom_bar(position = "dodge") +
  geom_text(aes(label = ..count..), stat = "count", position = position_dodge(0.9), vjust = -0.5) +
  scale_fill_manual(values = c("#b2182b","#2166ac"))

UCD.3vs2 <- DEG.merged[DEG.merged$Comparison == "UCD.3vs2",]
TCD.2vs1 <- DEG.merged[DEG.merged$Comparison == "TCD.2vs1",]
G2.UCDvsTCD <- DEG.merged[DEG.merged$Comparison == "G2.UCDvsTCD",]

p.volcan1 <- EnhancedVolcano(UCD.3vs2, lab = UCD.3vs2$SYMBOL,
                title= "UCD.3vs2",
                x = 'log2FoldChange',
                y = 'padj',
                pCutoff = 0.01
) + xlim(-10, 10)
p.volcan2 <- EnhancedVolcano(TCD.2vs1, lab = TCD.2vs1$SYMBOL,
                title= "TCD.2vs1",
                x = 'log2FoldChange',
                y = 'padj',
                pCutoff = 0.01
) + xlim(-10, 10)
p.volcan3 <- EnhancedVolcano(G2.UCDvsTCD, lab = G2.UCDvsTCD$SYMBOL,
                title= "G2.UCDvsTCD",
                x = 'log2FoldChange',
                y = 'padj',
                pCutoff = 0.01
) + xlim(-10, 10)

##OUTPUT

pdf(file = "./output/plots/DEG_clusters_overview.pdf", width=6, height=4.5,  family = "ArialMT")
theme.plain(p)
dev.off()

pdf(file = "./output/plots/DEG_clusters_vulcanos.pdf", width=6, height=6,  family = "ArialMT")
theme.plain(p.volcan1) + theme(legend.position = "none")
theme.plain(p.volcan2) + theme(legend.position = "none")
theme.plain(p.volcan3) + theme(legend.position = "none")
dev.off()