#Script generated by: Aaron D. Ramirez-Sanchez 
#Goal: To format metadata and create a sample_sample conversion

##ENVIRONMENT
library(ggplot2)
library(EnhancedVolcano)
library(dplyr)

##FUNCTIONS
#####PLOTS

theme.plain <- function(p, base_size = 10, base_family = "ArialMT") {
  p <- p + theme_linedraw(base_size = base_size, base_family = base_family) %+replace%
    theme(panel.background = element_blank(),
          #panel.border = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.line = element_line(color="black", size=0.75),
          axis.ticks = element_line(size=0.75),
          axis.text = element_text(size=base_size, family="ArialMT", face="plain"),
          strip.background = element_blank(),
          strip.text = element_text(size=base_size, family="ArialMT", face="plain"),
          legend.key = element_blank(),
          legend.text = element_text(size=base_size, family = "ArialMT", face="plain"),
          complete = TRUE,
          plot.title = element_text(hjust=0.5))
  return(p)
}


##INPUT
coldata <- read.delim(file = "./data/processed/metadata/extended_metadata.tsv", sep = "\t", row.names = 1)

#reading merged DEG 
DEG.merged <- read.csv(file = "./output/tables/DEG/extended_comparisons_merged.csv", header = T, stringsAsFactors = F)

#reading references genes
Ref.genes <- read.table(file = "./data/raw/reference/Prioritised_genes_van_der_Graaf.txt", header = F, stringsAsFactors = F)
Ref.genes <- Ref.genes$V1

all.Ref.genes <- read.table(file = "./data/raw/reference/All_genes_van_der_Graaf.txt", header = F, stringsAsFactors = F)
all.Ref.genes <- all.Ref.genes$V1

#Filters used for the DEG
L2FC.filter <- 1.0
p.adj.filter <- 0.01

RNA.ref <- read.table("/Users/R_projects/Oslo/results/eQTL/references/Homo_sapiens.GRCh37.75.genes.bed", sep = "\t", header = F)
names(RNA.ref) <- c("chr", "start_pos", "end_pos", "strand", "ENSEMBL", "SYMBOL")
RNA.ref <- RNA.ref[!duplicated(RNA.ref$ENSEMBL),]
Y.genes <- RNA.ref[RNA.ref$chr == "Y", ]$ENSEMBL

#colors: Danger Red, Tap Shoe and Blue Blossom
pallete_condition <- c("#D9514E", "#2A2B2D", "#2DA8D8")
#colors: Danger Red and 1/2, Tap Shoe and 1/2; and Blue Blossom and 1/2
pallete_condition_updown <- c("#D9514E","#FFACAA", "#2A2B2D","#6B6E73", "#2DA8D8","#7ECDEA")

##MAIN

#Filtering data
DEG.merged <- DEG.merged[(abs(DEG.merged$log2FoldChange) > L2FC.filter & !is.na(DEG.merged$log2FoldChange)) & 
                           (DEG.merged$padj < p.adj.filter & !is.na(DEG.merged$padj)), ]
DEG.merged$Direction <- factor(DEG.merged$Direction, levels = c("Upregulated", "Downregulated"))
DEG.merged <- DEG.merged[!DEG.merged$ENSEMBL %in% Y.genes, ]


names(DEG.merged)
#Adding extra column when ref gene is present
DEG.merged$Prioritized_2020 <- DEG.merged$ENSEMBL %in% Ref.genes
DEG.merged$GWAS_gene_2020 <- DEG.merged$ENSEMBL %in% all.Ref.genes


DEG.merged.minimal <- DEG.merged[,c("ENSEMBL", "SYMBOL", "ENTREZID", "Comparison", "log2FoldChange", "Cluster", "Prioritized_2020", "GWAS_gene_2020")]
DEG.merged.minimal <- tidyr::spread(DEG.merged.minimal, Comparison, log2FoldChange)

table(DEG.merged.minimal$Prioritized_2020)
table(DEG.merged.minimal$Cluster)
table(DEG.merged.minimal$GWAS_gene_2020)
table(DEG.merged.minimal$Prioritized_2020, DEG.merged.minimal$Cluster)
table(DEG.merged.minimal$GWAS_gene_2020, DEG.merged.minimal$Cluster)

DEG.GWAS <- DEG.merged.minimal[DEG.merged.minimal$GWAS_gene_2020 == TRUE,]

fisher.test(matrix(c(23, 248, 62, 1529), nrow = 2), alternative = "two.sided")

DEG.prioritized <- DEG.merged[DEG.merged$Prioritized_2020 == TRUE,]
table(DEG.prioritized$SYMBOL, DEG.prioritized$Cluster)

write.csv(DEG.prioritized, 
          file="./output/tables/DEG/DEG.prioritized_merged.csv", 
          row.names = F, quote = F)
